_target_: src.models.blip_module.LitBlip

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-5
  weight_decay: 0.05

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: 5

net:
  _target_: src.models.components.blip.BLIP_Decoder
  med_config: '/DATA1/ailinliu/Lightning/configs/model/med_config.json' 
  image_size: 224
  vit: 'base'
  vit_grad_ckpt: False
  vit_ckpt_layer: 0
  prompt: 'a picture of '

