CONFIG: "./configs/BLIP.yaml"
CHECKPOINT:
PRETRAINED:
OUTPUT_DIR: "output/generation"
TEXT_ENCODER: "bert-base-uncased"
TEXT_DECODER: "bert-base-uncased"
DEVICE: "cuda"
SEED: 42
WORLD_SIZE: 1
DIST_URL: "env://"
DISTRIBUTED: False
IMAGE_DIR: "./dataset/iu_xray/images&/DATA1/llm-research/MIMIC-CXR/files"
ANN_PATH: "./annotations/iu-annotation.json&./annotations/mimic_annotation.json"
KNOWLEDGE_PATH: "./annotations/iu_train_kg_AO.json&./annotations/mimic_train_kg_AO.json"
DATASET_NAME: "mimic_cxr"
MAX_SEQ_LENGTH: 90
THRESHOLD: 3
NUM_WORKER: 2
BATCH_SIZE: 2
VISUAL_EXTRACTOR: "resnet101"
VISUAL_EXTRACTOR: True
D_MODEL: 512
D_FF: 512
D_VF: 2048
NUM_HEADS: 8
NUM_LAYERS: 3
DROUPOUT: 0.1
LOGIT_LAYERS: 1
BOS_IDX: 0
EOS_IDX: 0
PAD_IDX: 0
USE_BN: 0
DROP_PROB_LM: 0.5
SAMPLE_METHOD: "beam_search"
BEAM_SIZE: 3
TEMPERATURE: 1.0
SAMPLE_N: 1
GROUP_SIZE: 1
OUTPUT_LOGSOFTMAX: 1
DECODING_CONSTRAINT: 0
BLOCK_TRIGRAMS: 1
N_GPU: 1
EPOCHS: 30
SAVE_DIR: "results/fair"
RECORD_DIR: "records/generation/"
SAVE_PERIOD: 1
MONITOR_MODE: max
EARLY_STOP: 50
OPTIM: "Adam"
LR_VE: 1e-5
LR_ED: 1e-4
WEIGHT_DECAY: 5e-5
AMSGRAD: True
LR_SCHEDULER: "StepLR"
STEP_SIZE: 50
GAMMA: 0.1
TEXT_VISUAL: False
TEST_TEXT: False
TEST_TEXT_CROSS: False
TEST_VISUAL_TEXT: False
TEST_BEST: False
ADD_MEMORY: False
TOKENIZER: "blip"
BERT: "base"
CONCAT: False
TASK: "pretrain"